import { v4 as uuidv4 } from 'uuid';
import type { AppData } from '../types';
import { ensureDefaultCareProviders } from '../utils/profileDefaults';

const now = new Date().toISOString();
const daysFromNow = (days: number) => {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().split('T')[0];
};
const daysAgo = (days: number) => daysFromNow(-days);

export function createSampleData(): AppData {
  const appt1Id = uuidv4();
  const appt2Id = uuidv4();
  const appt3Id = uuidv4();
  const med1Id = uuidv4();
  const med2Id = uuidv4();
  const cond1Id = uuidv4();
  const cond2Id = uuidv4();

  return {
    appointments: [
      {
        id: appt1Id,
        doctorName: 'Dr. Sarah Chen',
        specialty: 'Primary Care',
        clinic: 'Riverside Medical Center',
        date: daysFromNow(5),
        time: '10:30',
        reason: 'Annual physical exam',
        symptoms: 'Mild fatigue, occasional headaches',
        questionsToAsk: 'Should I get blood work? Any vaccine updates?',
        diagnosis: '',
        treatmentPlan: '',
        followUpNeeded: false,
        nextAppointmentDate: '',
        cost: '$25 copay',
        notes: 'Bring insurance card and medication list',
        status: 'upcoming',
        providerId: '',
        healthCategory: 'core_medical',
        relatedConditionIds: [],
        relatedMedicationIds: [],
        relatedRecordIds: [],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: appt2Id,
        doctorName: 'Dr. James Patel',
        specialty: 'Cardiology',
        clinic: 'Heart & Vascular Institute',
        date: daysFromNow(14),
        time: '14:00',
        reason: 'Follow-up on blood pressure',
        symptoms: '',
        questionsToAsk: 'Is my current medication dosage correct?',
        diagnosis: '',
        treatmentPlan: '',
        followUpNeeded: false,
        nextAppointmentDate: '',
        cost: '$40 copay',
        notes: '',
        status: 'upcoming',
        providerId: '',
        healthCategory: 'core_medical',
        relatedConditionIds: [cond1Id],
        relatedMedicationIds: [med1Id],
        relatedRecordIds: [],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: appt3Id,
        doctorName: 'Dr. Sarah Chen',
        specialty: 'Primary Care',
        clinic: 'Riverside Medical Center',
        date: daysAgo(30),
        time: '09:00',
        reason: 'Sinus infection',
        symptoms: 'Congestion, facial pressure, low-grade fever',
        questionsToAsk: 'Do I need antibiotics?',
        diagnosis: 'Acute sinusitis',
        treatmentPlan: '10-day antibiotic course, rest, fluids',
        followUpNeeded: true,
        nextAppointmentDate: daysAgo(15),
        cost: '$20 copay',
        notes: 'Symptoms improved after 5 days',
        status: 'completed',
        providerId: '',
        healthCategory: 'core_medical',
        relatedConditionIds: [],
        relatedMedicationIds: [],
        relatedRecordIds: [],
        createdAt: now,
        updatedAt: now,
      },
    ],
    conditions: [
      {
        id: cond1Id,
        name: 'Hypertension',
        dateDiagnosed: '2022-03-15',
        doctor: 'Dr. James Patel',
        status: 'chronic',
        notes: 'Managed with lifestyle changes and medication. Target BP under 130/80.',
        relatedMedicationIds: [med1Id],
        relatedAppointmentIds: [appt2Id],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: cond2Id,
        name: 'Seasonal Allergies',
        dateDiagnosed: '2019-04-10',
        doctor: 'Dr. Sarah Chen',
        status: 'active',
        notes: 'Worse in spring. Use antihistamines as needed.',
        relatedMedicationIds: [med2Id],
        relatedAppointmentIds: [],
        createdAt: now,
        updatedAt: now,
      },
    ],
    medications: [
      {
        id: med1Id,
        name: 'Lisinopril',
        dose: '10mg',
        frequency: 'Once daily',
        startDate: '2022-04-01',
        endDate: '',
        prescribingDoctor: 'Dr. James Patel',
        reason: 'Hypertension',
        sideEffects: 'Occasional dry cough',
        active: true,
        notes: 'Take in the morning with water',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: med2Id,
        name: 'Loratadine',
        dose: '10mg',
        frequency: 'Once daily as needed',
        startDate: '2024-03-01',
        endDate: '2024-06-30',
        prescribingDoctor: 'Dr. Sarah Chen',
        reason: 'Seasonal allergies',
        sideEffects: 'None reported',
        active: true,
        notes: 'Non-drowsy formula',
        createdAt: now,
        updatedAt: now,
      },
    ],
    records: [
      {
        id: uuidv4(),
        recordType: 'lab',
        date: daysAgo(45),
        uploadDate: daysAgo(45),
        provider: 'Riverside Lab',
        summary: 'Complete blood count — all values within normal range',
        notes: 'Cholesterol slightly elevated at 210',
        fileName: 'cbc_results_2024.pdf',
        extractedText: '',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: uuidv4(),
        recordType: 'vaccine',
        date: '2024-10-15',
        uploadDate: '2024-10-15',
        provider: 'Riverside Medical Center',
        summary: 'Annual flu vaccine administered',
        notes: 'No adverse reactions',
        fileName: '',
        extractedText: '',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: uuidv4(),
        recordType: 'imaging',
        date: daysAgo(90),
        uploadDate: daysAgo(90),
        provider: 'Heart & Vascular Institute',
        summary: 'Echocardiogram — normal ejection fraction',
        notes: 'Routine cardiac screening',
        fileName: 'echo_report.pdf',
        extractedText: '',
        createdAt: now,
        updatedAt: now,
      },
    ],
    healthNotes: [
      {
        id: uuidv4(),
        title: 'Emergency Contacts',
        content:
          'Primary: Jane Doe (spouse) — 555-0100\nDoctor on call: Riverside Medical — 555-0200\nPharmacy: CVS on Main St — 555-0300',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: uuidv4(),
        title: 'Allergies',
        content: 'Penicillin — causes rash\nShellfish — mild reaction',
        createdAt: now,
        updatedAt: now,
      },
    ],
    adultHealthProfile: ensureDefaultCareProviders({
      name: 'Alex Morgan',
      dateOfBirth: '1990-06-15',
      pharmacy: {
        name: 'CVS Pharmacy — Main St',
        phone: '555-0300',
        location: '123 Main St, Riverside',
      },
      emergencyContact: {
        name: 'Jordan Morgan',
        phone: '555-0100',
        relationship: 'Spouse',
      },
      insuranceMedical: {
        carrier: 'BlueCross Health',
        planName: 'PPO Gold',
        memberIdHint: '…4821',
        groupNumber: 'GRP-99201',
        phone: '800-555-1234',
        portalUrl: 'https://member.bluecross.example.com',
        portalNotes: 'Login with email; use password manager',
        notes: 'Card on file in wallet',
      },
      insuranceDental: {
        carrier: 'Delta Dental',
        planName: 'Premier',
        memberIdHint: '…7732',
        groupNumber: '',
        phone: '800-555-5678',
        portalUrl: '',
        portalNotes: '',
        notes: '',
      },
      insuranceVision: {
        carrier: 'VSP',
        planName: 'Standard',
        memberIdHint: '…1190',
        groupNumber: '',
        phone: '800-555-9012',
        portalUrl: 'https://vsp.example.com',
        portalNotes: '',
        notes: '',
      },
      careProviders: [
        {
          id: uuidv4(),
          category: 'core_medical',
          providerName: 'Dr. Sarah Chen',
          specialty: 'Primary Care',
          location: 'Riverside Medical Center',
          phone: '555-0200',
          lastVisit: daysAgo(400),
          scheduledVisit: daysFromNow(5),
          nextDueOverride: '',
          dueFrequency: 'yearly',
          customFrequencyMonths: 12,
          notes: 'Annual physical due',
          portalNotes: 'MyChart portal',
          enabled: true,
        },
        {
          id: uuidv4(),
          category: 'vaccines_labs',
          providerName: 'Riverside Lab',
          specialty: 'Preventive Care / Labs',
          location: 'Riverside Medical Center',
          phone: '555-0201',
          lastVisit: daysAgo(45),
          scheduledVisit: '',
          nextDueOverride: '',
          dueFrequency: 'yearly',
          customFrequencyMonths: 12,
          notes: 'Flu vaccine Oct 2024',
          portalNotes: '',
          enabled: true,
        },
        {
          id: uuidv4(),
          category: 'womens_health',
          providerName: 'Dr. Emily Wong',
          specialty: 'OB-GYN',
          location: 'Women\'s Health Associates',
          phone: '555-0400',
          lastVisit: daysAgo(380),
          scheduledVisit: '',
          nextDueOverride: '',
          dueFrequency: 'yearly',
          customFrequencyMonths: 12,
          notes: '',
          portalNotes: '',
          enabled: true,
        },
        {
          id: uuidv4(),
          category: 'sexual_health',
          providerName: 'Riverside Clinic',
          specialty: 'Sexual Health',
          location: 'Riverside Medical Center',
          phone: '555-0200',
          lastVisit: daysAgo(200),
          scheduledVisit: '',
          nextDueOverride: '',
          dueFrequency: 'yearly',
          customFrequencyMonths: 12,
          notes: 'STI screening',
          portalNotes: '',
          enabled: true,
        },
        {
          id: uuidv4(),
          category: 'dental',
          providerName: 'Dr. Mike Rivera',
          specialty: 'General Dentistry',
          location: 'Bright Smile Dental',
          phone: '555-0500',
          lastVisit: daysAgo(200),
          scheduledVisit: daysFromNow(20),
          nextDueOverride: '',
          dueFrequency: 'six_months',
          customFrequencyMonths: 6,
          notes: 'Cleaning scheduled',
          portalNotes: '',
          enabled: true,
        },
        {
          id: uuidv4(),
          category: 'vision',
          providerName: 'Dr. Lisa Park',
          specialty: 'Optometry',
          location: 'ClearView Optometry',
          phone: '555-0600',
          lastVisit: daysAgo(300),
          scheduledVisit: '',
          nextDueOverride: '',
          dueFrequency: 'yearly',
          customFrequencyMonths: 12,
          notes: '',
          portalNotes: '',
          enabled: true,
        },
        {
          id: uuidv4(),
          category: 'dermatology',
          providerName: '',
          specialty: 'Dermatology',
          location: '',
          phone: '',
          lastVisit: '',
          scheduledVisit: '',
          nextDueOverride: '',
          dueFrequency: 'optional_yearly',
          customFrequencyMonths: 12,
          notes: 'Optional — add provider if needed',
          portalNotes: '',
          enabled: false,
        },
        {
          id: uuidv4(),
          category: 'mental_health',
          providerName: 'Dr. Anna Brooks',
          specialty: 'Therapist',
          location: 'MindWell Counseling',
          phone: '555-0700',
          lastVisit: daysAgo(30),
          scheduledVisit: daysFromNow(14),
          nextDueOverride: '',
          dueFrequency: 'custom',
          customFrequencyMonths: 4,
          notes: 'Therapy every 4 months',
          portalNotes: '',
          enabled: true,
        },
      ],
      profileNotes: 'Blood type: O+',
      updatedAt: now,
    }),
    settings: { theme: 'light' },
  };
}
